variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone  
  name: dmajoros
  password: Peper2000


#image: docker:19.03.12
#services:
#  - docker:19.03.12-dind

image: docker:stable
services:
  - docker:dind


stages:
  - Build

build_job:
  stage: Build
  script:
    - docker login -u "$name" --password "$password"
    - docker build -t dmajoros/repa:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/repa:latest
    - docker logout