variables:
  GIT_SSL_NO_VERIFY: "true"
  GIT_STRATEGY: clone  

stages:
  - build
  - deploy
  - test
  - destroy

build-job:
  stage: build
  image: docker
  services: 
    - docker:dind
  tags:
    - otc_run_docker_m 
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t dmajoros/repa:latest -f Dockerfile .
    - docker image ls
    - docker push dmajoros/repa:latest
    - docker logout
  when: manual

deploy-job:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  tags:
    - otc_run_docker_k8s_xl
  script:
    - kubectl config use-context david.majoros/k3s-connection:k3s-connection
    - kubectl get node -o wide
    - |
      if ! kubectl get namespace prod &> /dev/null; then
        kubectl create namespace prod
      else
        echo "Namespace 'prod' already exists, skipping creation."
      fi
    - kubectl apply -f repa-prod/deployment.yaml
    - kubectl apply -f repa-prod/service.yaml
  when: manual

test-job:
  stage: test
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  tags:
    - otc_run_docker_k8s_xl
  script:
    - kubectl config use-context david.majoros/k3s-connection:k3s-connection
    - kubectl get node -o wide
    - kubectl get namespace 
    - kubectl get pod -n prod -o wide
    - kubectl get service -n prod -o wide
  when: manual

destroy-job:
  stage: destroy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  tags:
    - otc_run_docker_k8s_l
  script:
    - kubectl config use-context david.majoros/k3s-connection:k3s-connection
    - kubectl delete deployment repa-app -n prod
    - kubectl delete service repa-app -n prod
    - kubectl delete namespace prod
    - kubectl get namespace 
  when: manual


