apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: repa-app
  name: repa-app
  namespace: prod
spec:
  ports:
  - name: repa-app
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: repa-app
  type: NodePort
status:
  loadBalancer: {}
